[package]
name = "pernix_lexical_input"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pernix_input = { path = "../pernix_input"}
pernixc_lexical = { path = "../../compiler/pernixc_lexical" }
pernixc_source = { path = "../../compiler/pernixc_source" }
pernixc_system = { path = "../../compiler/pernixc_system" }
proptest = { workspace = true }
derive_more = { workspace = true }
strum = { workspace = true }
lazy_static = { workspace = true }