[package]
name = "pernixc_driver"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
pernixc_source_file = { path = "../pernixc_source_file" }
pernixc_diagnostic = { path = "../pernixc_diagnostic" }
pernixc_handler = { path = "../pernixc_handler" }
pernixc_syntax = { path = "../pernixc_syntax" }
pernixc_table = { path = "../pernixc_table" }
pernixc_builder = { path = "../pernixc_builder" }
pernixc_log = { path = "../pernixc_log" }
pernixc_intrinsic = { path = "../pernixc_intrinsic" }
pernixc_codegen = { path = "../pernixc_codegen" }
pernixc_storage = { path = "../pernixc_storage" }
ron = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
indicatif = { workspace = true }
parking_lot = { workspace = true }
inkwell = { workspace = true }

[lints]
workspace = true
