[package]
name = "pernixc_driver"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
pernixc_base = { path = "../pernixc_base" }
pernixc_lexical = { path = "../pernixc_lexical" }
pernixc_syntax = { path = "../pernixc_syntax" }
pernixc_semantic = { path = "../pernixc_semantic" }
rayon = { workspace = true }
