[package]
name = "pernix_syntax_input"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
pernix_input = { path = "../pernix_input"}
pernix_lexical_input = { path = "../pernix_lexical_input"}
pernixc_syntax = { path = "../../compiler/pernixc_syntax" }
pernixc_source = { path = "../../compiler/pernixc_source" }
pernixc_system = { path = "../../compiler/pernixc_system" }
pernixc_lexical = { path = "../../compiler/pernixc_lexical" }
enum-as-inner = { workspace = true }
proptest = { workspace = true }
derive_more = { workspace = true }
strum = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }