[workspace]
members = [
    "compiler/pernixc_common",
    "compiler/pernixc_lexical",
    "compiler/pernixc_syntax",
    "compiler/pernixc_semantic",
    "compiler/pernixc_driver"
]

[workspace.dependencies]
enum-as-inner = "0.5.1"
thiserror = "1.0.40"
getset = "0.1.2"
proptest = "1.1.0"
lazy_static = "1.4.0"
strum = "0.24.1"
strum_macros = "0.24"
delegate = "0.9.0"
derive-new = "0.5.9"