[workspace]
members = [
    "compiler/pernixc_system",
    "compiler/pernixc_source",
    "compiler/pernixc_print",
    "compiler/pernixc_lexical",
    "compiler/pernixc_syntax",
    "compiler/pernixc_symbol",

    "inputs/pernix_input",
    "inputs/pernix_lexical_input",
    "inputs/pernix_syntax_input"
]

[workspace.dependencies]
enum-as-inner = "0.6.0"
thiserror = "1.0.40"
getset = "0.1.2"
proptest = "1.1.0"
lazy_static = "1.4.0"
strum = "0.25.0"
strum_macros = "0.25"
derive_more = "0.99.17"
colored = "2.0.0"
paste = "1.0.12"
tempfile = "3.5.0"
by_address = "1.1.0"
quickcheck = "1.0.3"
itertools = "0.11.0"

[workspace.package]
version = "0.1.0"
authors = ["Simmypeet"]
description = "The Pernix Programming Language Compiler"
edition = "2021"
