[workspace]
members = [
    "compiler/pernixc_system",
    "compiler/pernixc_common",
    "compiler/pernixc_lexical",
    "compiler/pernixc_syntax",
    "compiler/pernixc_semantic",
]

[workspace.dependencies]
enum-as-inner = "0.5.1"
thiserror = "1.0.40"
getset = "0.1.2"
proptest = "1.1.0"
lazy_static = "1.4.0"
strum = "0.24.1"
strum_macros = "0.24"
derive-new = "0.5.9"
derive_more = "0.99.17"
colored = "2.0.0"
builder-pattern = "0.4.2"
derive-getters = "0.2.1"
paste = "1.0.12"
delegate = "0.9.0"

[workspace.package]
version = "0.1.0"
authors = ["Simmypeet"]
description = "The Pernix Programming Language Compiler"
edition = "2021"
