//! Contains the code related to the symbol resolution pass of the compiler.

use std::sync::atomic::AtomicU64;

// pub mod errors;
pub mod item;
pub mod ty;

pub(crate) type Uid = u64;

/// Generates a new [`Uid`] that is guaranteed to be unique from any others generated by this
/// function.
pub(crate) fn new_uid() -> Uid {
    // use u64 atomic counter
    static COUNTER: AtomicU64 = AtomicU64::new(0);

    COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
}
