[package]
name = "pernixc_syntax"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
arbitrary = [
    "dep:proptest",
    "pernixc_lexical/arbitrary",
    "dep:pernixc_test_input",
]

[dependencies]
pernixc_lexical = { path = "../pernixc_lexical" }
pernixc_parser = { path = "../pernixc_parser" }
pernixc_test_input = { path = "../pernixc_test_input", optional = true }
pernixc_stable_type_id = { path = "../pernixc_stable_type_id" }
proptest = { workspace = true, optional = true }
enum-as-inner = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
pernixc_source_file = { path = "../pernixc_source_file" }
pernixc_lexical = { path = "../pernixc_lexical", features = ["arbitrary"] }
pernixc_test_input = { path = "../pernixc_test_input" }
pernixc_target = { path = "../pernixc_target" }
pernixc_handler = { path = "../pernixc_handler" }
proptest = { workspace = true }

[lints]
workspace = true
