[package]
name = "pernixc_syntax"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pernixc_lexical = { path = "../pernixc_lexical" }
pernixc_common = { path = "../pernixc_common" }
enum-as-inner = { workspace = true }
thiserror = { workspace = true }
getset = { workspace = true }
lazy_static = { workspace = true }
derive_more = { workspace = true }
derive-getters = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
