[package]
name = "pernixc_syntax"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pernixc_base = { path = "../pernixc_base" }
pernixc_lexical = { path = "../pernixc_lexical" }
enum-as-inner = { workspace = true }
thiserror = { workspace = true }
getset = { workspace = true }
lazy_static = { workspace = true }
derive_more = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
pernixc_tests = { path = "../pernixc_tests" }
proptest = { workspace = true }
