[package]
name = "pernixc_syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pernixc_lexical = { path = "../pernixc_lexical" }
pernixc_common = { path = "../pernixc_common" }
enum-as-inner = "0.5.1"
thiserror = "1.0.26"
proptest = "1.1.0"