[package]
name = "pernixc_handler"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
derive_more = { workspace = true }
parking_lot = { workspace = true }

[lints]
workspace = true
