[package]
name = "pernixc_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }

