[package]
name = "pernixc_system"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }
proptest = { workspace = true }
parking_lot = { workspace = true }
