[package]
name = "pernixc_term"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
arbitrary = ["dep:proptest"]

[dependencies]
pernixc_serialize = { path = "../../base/serialize" }
pernixc_target = { path = "../../base/target" }
pernixc_query = { path = "../../base/query" }
pernixc_arena = { path = "../../base/arena" }
pernixc_hash = { path = "../../base/hash" }
pernixc_lexical = { path = "../../syntax/lexical" }
pernixc_stable_hash = { path = "../../base/stable_hash" }
pernixc_symbol = { path = "../symbol" }
enum-as-inner = { workspace = true }
derive_more = { workspace = true }
getset = { workspace = true }
paste = { workspace = true }
thiserror = { workspace = true }
derive-new = { workspace = true }
proptest = { workspace = true, optional = true }

[lints]
workspace = true
