[package]
name = "pernixc_register"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_query = { path = "../query" }
pernixc_serialize = { path = "../serialize" }
inventory = { workspace = true }

[lints]
workspace = true
