[package]
name = "pernixc_query"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
query_cache = []
default = ["query_cache"]

[dependencies]
pernixc_stable_hash = { path = "../../base/stable_hash" }
pernixc_query_derive = { path = "../query_derive" }
pernixc_stable_type_id = { path = "../../base/stable_type_id" }
pernixc_serialize = { path = "../../base/serialize" }
pernixc_hash = { path = "../../base/hash" }
parking_lot = { workspace = true }
smallbox = { workspace = true }
getset = { workspace = true }
enum-as-inner = { workspace = true }
dashmap = { workspace = true }
rayon = { workspace = true }
redb = { workspace = true }
tracing = { workspace = true }
crossbeam = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
static_assertions = { workspace = true }

[dev-dependencies]
ron = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }


[lints]
workspace = true
