[package]
name = "pernixc_semantic"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pernixc_common = { path = "../pernixc_common" }
pernixc_syntax = { path = "../pernixc_syntax" }
pernixc_lexical = { path = "../pernixc_lexical" }
enum-as-inner = { workspace = true }
thiserror = { workspace = true }
derive-new = { workspace = true }
getset = { workspace = true }
derive_more = { workspace = true }
builder-pattern = { workspace = true }
derive-getters = { workspace = true }
paste = { workspace = true }