[package]
name = "pernix_server"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
getset = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
by_address = { workspace = true }

pernixc_source_file = { path = "../../compiler/pernixc_source_file" }
pernixc_diagnostic = { path = "../../compiler/pernixc_diagnostic" }
pernixc_handler = { path = "../../compiler/pernixc_handler" }
pernixc_lexical = { path = "../../compiler/pernixc_lexical" }
pernixc_syntax = { path = "../../compiler/pernixc_syntax" }
pernixc_log = { path = "../../compiler/pernixc_log" }
pernixc_table = { path = "../../compiler/pernixc_table" }
pernixc_builder = { path = "../../compiler/pernixc_builder" }

[lints]
workspace = true
