//! Contains the definition of the [`ElidedLifetimes`] component.

use pernixc_arena::{Arena, ID};
use pernixc_semantic::{component::Derived, MemberID};
use serde::{Deserialize, Serialize};

/// Represents a lifetime that has been generated implicitly by the compiler
/// in the case where the lifetime is elided such as `number: &int32`.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Serialize,
    Deserialize,
)]
pub struct ElidedLifetime {}

/// A **presistent-derived** component storing all the generated elided
/// lifetimes.
///
/// This component can only be found in the function symbol.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ElidedLifetimes {
    /// List of all the elided lifetimes that have been generated by the
    /// compiler.
    pub elided_lifetimes: Arena<ElidedLifetime>,
}

impl Derived for ElidedLifetimes {
    fn component_name() -> &'static str { "elided lifetimes" }
}

/// The ID to a elided lifetime.
pub type ElidedLifetimeID = MemberID<ID<ElidedLifetime>>;
