[package]
name = "pernixc_serialize"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pernixc_serialize_derive = { path = "../serialize_derive" }
dashmap = { workspace = true }
flexstr = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
pernixc_serialize_derive = { path = "../serialize_derive" }
