[package]
name = "pernixc_test"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
pernixc_source_file = { path = "../pernixc_source_file" }
pernixc_memory_checker = { path = "../pernixc_memory_checker" }
pernixc_borrow_checker = { path = "../pernixc_borrow_checker" }
pernixc_resolution = { path = "../pernixc_resolution" }
pernixc_syntax = { path = "../pernixc_syntax" }
pernixc_semantic = { path = "../pernixc_semantic" }
pernixc_builder = { path = "../pernixc_builder" }
pernixc_ir = { path = "../pernixc_ir" }
pernixc_type_system = { path = "../pernixc_type_system" }
pernixc_driver = { path = "../pernixc_driver" }
assert_cmd = { workspace = true }
tempfile = { workspace = true }


[[test]]
name = "memory_checker"
path = "src/memory_checker.rs"

[[test]]
name = "borrow_checker"
path = "src/borrow_checker.rs"

[[test]]
name = "codegen"
path = "src/codegen/mod.rs"


[lints]
workspace = true
